package com.arham.demo_project.Services;

import com.arham.demo_project.Model.Book;
import com.arham.demo_project.Model.Report;
import com.arham.demo_project.Repositry.ReportRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.NoSuchElementException;

@Service
public class ReportService {

    @Autowired
    private ReportRepository repo;
    @Autowired
    private BookService bookService;
    @Autowired
    private UserService userService;

    public List<Report> viewbooks(){
        List<Report> report= repo.findAll();
        if(! report.isEmpty()) return report;
        else
            throw new NoSuchElementException("Nothing borrowed till now");
    }

    public boolean findUserInReporttable(Long id){
        return repo.finduserbyid(id);
    }

    public List<Report> getissuedbook(Long userid){
        return repo.getbooklistofuser(userid);
    }

    public boolean findbookbyid(Long book_id){
        return repo.findbookbyid(book_id);
    }

    public List<Report> getbooksinfo(Long book_id){
        return repo.getbooksinfo(book_id);
    }

    public boolean doesbothexistsandhavenull(Long userid,Long book_id){
        return repo.doesbothexistsandhavenull(userid,book_id);
    }

    public void insertentry(Report r1){
        repo.save(r1);
    }

    public void updatefine(Long member_id, Long book_id, int value){
        repo.updatefine(member_id, book_id, value);
    }

    public Timestamp getissuedate(Long userid,Long book_id){
        return repo.getissuedate(userid,book_id);
    }

    public boolean howManybooks(Long id){
        if(!repo.howManybooks(id)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Borrow Limit already reached");
        return repo.howManybooks(id);
    }

    public void updateReturnDate(Long userid, Long book_id){
        repo.updateReturnDate(userid,book_id);
    }

    @Transactional
    public Report issueBook(Report r1){
        Long BookId = r1.getBook_id();
        Long MemberId = r1.getMember_id();

        // Lock the book row first — concurrent issues of the same book serialize here.
        Book book = bookService.getBookForUpdate(BookId);

        // Consistency checks, now INSIDE the transaction and on the locked row.
        if(book.getIssue_quantity() >= book.getTotal_quantity())
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "book is unavailable");
        howManybooks(MemberId); // throws FORBIDDEN if borrow limit reached
        if(doesbothexistsandhavenull(MemberId, BookId))
            throw new ResponseStatusException(HttpStatus.CONFLICT, "Book is already with user");

        // All rules passed — write.
        r1.setBorrow_id(null);   // autogenerated attribute
        r1.setReturn_date(null);
        r1.setFine_amount(0);
        book.setIssue_quantity(book.getIssue_quantity() + 1); // dirty-checked, flushed on commit
        repo.save(r1);
        return r1;
    }

    @Transactional
    public void returnBook(Long MemberId, Long BookId){
        Timestamp issued = getissuedate(MemberId, BookId);

        // Lock the book row before decrementing its count.
        Book book = bookService.getBookForUpdate(BookId);

        long datediff = ChronoUnit.DAYS.between(issued.toLocalDateTime(), LocalDateTime.now());
        int value = (int) Math.max(0, datediff - 14) * 2; // fine = 2 currency/day
        updatefine(MemberId, BookId, value);
        userService.updateTotalDues(MemberId, value);
        updateReturnDate(MemberId, BookId);
        book.setIssue_quantity(book.getIssue_quantity() - 1); // dirty-checked, flushed on commit
    }
}
