package com.arham.demo_project.Model;

import jakarta.persistence.*;

import java.util.NoSuchElementException;

@Entity
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;
    private int total_quantity;
    private int issue_quantity;
    private float book_price;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getTotal_quantity() {
        return total_quantity;
    }

    public void setTotal_quantity(int total_quantity) {
        this.total_quantity = total_quantity;
    }

    public int getIssue_quantity() {
        return issue_quantity;
    }

    public void setIssue_quantity(int issue_quantity) {
        this.issue_quantity = issue_quantity;
    }

    public float getBook_price() {
        return book_price;
    }

    public void setBook_price(float book_price) {
        this.book_price = book_price;
    }

    public boolean bookValidator(Book b){
        String title= b.getTitle();
        int total_quantity=b.getTotal_quantity();
        int issue_quantity=b.getIssue_quantity();

        if(b.id != null) throw new IllegalArgumentException("You can't put id as attribute,id autogenerated");
        if(title.isEmpty() || total_quantity ==0) throw new NoSuchElementException("Title can't be empty or Total quatity can't be zero");
        if(total_quantity < issue_quantity) throw new ArithmeticException("Issue_quantity can't be greater than total_quantity");

        return true;
    }
}
