package com.arham.demo_project.Model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;

import static com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY;


@Entity
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Title is required")
    @Size(max = 200, message = "Title too long")
    @Pattern(regexp = ".*[a-zA-Z].*", message = "Title must contain letters")
    private String title;

    @Positive(message = "Total quantity must be greater than 0")
    private int total_quantity;

    @JsonProperty(access = READ_ONLY)
    private int issue_quantity;

    @Positive(message = "Book price should be greater than 0")
    private float book_price;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getTotal_quantity() {
        return total_quantity;
    }

    public void setTotal_quantity(int total_quantity) {
        this.total_quantity = total_quantity;
    }

    public int getIssue_quantity() {
        return issue_quantity;
    }

    public void setIssue_quantity(int issue_quantity) {
        this.issue_quantity = issue_quantity;
    }

    public float getBook_price() {
        return book_price;
    }

    public void setBook_price(float book_price) {
        this.book_price = book_price;
    }

    public boolean bookValidator(Book b){
        if(b.id != null) throw new IllegalArgumentException("You can't put id as attribute,id autogenerated");
        b.setIssue_quantity(0);
        return true;
    }
}
