package com.arham.demo_project.Model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;
import org.hibernate.annotations.CreationTimestamp;
import java.sql.Timestamp;

@Entity
public class Member {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true)
    @NotBlank(message = "Username is required")
    @Pattern(regexp = "^(?=.*[a-zA-Z]).{3,}$",
            message = "Username must contain letters, not just numbers")
    private String username;

    @NotBlank(message = "Password is required")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;
    private String name;
    private String role;

    @CreationTimestamp
    @Column(updatable = false)
    private Timestamp creation_date;

    @PositiveOrZero(message="total_dues should be greater than 0")
    private float total_dues;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Timestamp getCreation_date() {
        return creation_date;
    }

    public void setCreation_date(Timestamp creation_date) {
        this.creation_date = creation_date;
    }

    public float getTotal_dues() {
        return total_dues;
    }

    public void setTotal_dues(float total_dues) {
        this.total_dues = total_dues;
    }

    public Member memberValidation(Member user){
        if(user.id!=null) throw new IllegalArgumentException("You can't put id as attribute,id autogenerated");
        if(user.role==null || user.role.isEmpty()|| (!user.role.equalsIgnoreCase("MEMBER") && !user.role.equalsIgnoreCase("ADMIN"))) {
            user.setRole("MEMBER");
        } else {
            user.setRole(user.role.toUpperCase());
        }
        user.setTotal_dues(0);
        return user;
    }
}
