package com.arham.demo_project.model;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;

import java.sql.Timestamp;
import java.util.NoSuchElementException;

@Entity
public class member {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String username;

    private String password;
    private String name;
    private String role;

    @CreationTimestamp
    @Column(updatable = false)
    private Timestamp creation_date;

    private float total_dues;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Timestamp getCreation_date() {
        return creation_date;
    }

    public void setCreation_date(Timestamp creation_date) {
        this.creation_date = creation_date;
    }

    public float getTotal_dues() {
        return total_dues;
    }

    public void setTotal_dues(float total_dues) {
        this.total_dues = total_dues;
    }

    public member memberValidation(member user){
        if(user.id!=null) throw new IllegalArgumentException("You can't put id as attribute,id autogenerated");
        if(user.username.isEmpty()) throw new NoSuchElementException("Username can't be empty");
        if(user.password.isEmpty()) throw new NoSuchElementException("Password can't be empty");
        if(user.role.isEmpty()) {
            user.setRole("MEMBER");
        }
        return user;
    }
}
